--- 
- name: "update apt package"
  become: true
  apt:  
    update_cache: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: "autoremove unmet dependencies or broken apt package"
  become: true
  apt: 
    autoremove: yes

- name : "upgrade package"
  become: true
  apt: 
    upgrade: yes

- name:  "install nodejs and npm"
  become : true
  apt: 
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes
  
- name : "install pm2"
  become: true
  npm: 
    name: pm2 
    global: yes 
    production: yes
    state: present 
