---
- name: Creates App directory
  #become: true
  file:
    path: ~/app
    state: directory

- name: Upload app 
  #become: true
  copy:
    src: artifact.tar.gz
    dest: ~/app/
    
- name: Install dependencies
  #become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    #curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo apt-get install gcc g++ make -y
    sudo npm install -g npm
    sudo npm install -g pm2
    cd ~/app
    tar xzvf ~/app/artifact.tar.gz
  register: command_output

  
- name: Start backend
  #become: true
  shell:  |
    pm2 start ~/app/dist/main.js --name backend -f
  #pm2 start npm --name backend -- run start
  #pm2 start ~/app/dist/main.js --name backend -f
  #environment:
  #  ENVIRONMENT: production
  #  NODE_ENV: production
  #  TYPEORM_CONNECTION: postgres
  #  TYPEORM_MIGRATIONS_DIR: ~/app/src/migrations
  #  TYPEORM_MIGRATIONS: ~/app/src/migrations/*.ts
  #  TYPEORM_ENTITIES: ~/app/src/modules/domain/**/*.entity.ts
  #  TYPEORM_HOST: peopledatabase.ckk21qjne6sv.us-east-1.rds.amazonaws.com
  #  TYPEORM_PORT: 5432
  #  TYPEORM_USERNAME: postgres
  #  TYPEORM_PASSWORD: postgres123
  #  TYPEORM_DATABASE: postgres
  register: command_ouput

- name: Start app on backend
  #become: true
  shell:  |
    cd ~/app
    npm install --force
    pm2 stop default
    pm2 start npm -- start
  register: command_output

- debug:
    var: command_output.stdout_lines