---
- name: Creates App directory
  become: true
  file:
    path: ~/app
    state: directory
    
- name: Upload app 
  become: true
  copy:
    src: files/artifact.tar.gz
    dest: "~/app/"
    
- name: Install dependencies
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    apt-get install -y nodejs
    apt-get install gcc g++ make -y
    npm install -g npm
    npm install -g pm2
    cd ~/app
    tar xzvf ~/app/artifact.tar.gz
  
- name: Start backend
  shell:  |
    /usr/bin/pm2 start ~/app/dist/main.js --name backend -f
  environment:
    ENVIRONMENT: production
    NODE_ENV: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_MIGRATIONS_DIR: ~/app/src/migrations
    TYPEORM_MIGRATIONS: ~/app/src/migrations/*.ts
    TYPEORM_ENTITIES: ~/app/src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: peopledatabase.ckk21qjne6sv.us-east-1.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: postgres123
    TYPEORM_DATABASE: postgres

- name: Start app on backend
  become: true
  shell:  |
    cd ~/app/root/project/backend
    npm install
    pm2 stop default
    pm2 start npm -- start