version : 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-my-project-{{ checksum " project.clj"}}
            - v2-my-project-
      - run:
          name: Build front-end
          command: |
            npm install
            npm run build
      - save_cache:
          paths: 
            - /home/ubuntu/.m2
          key: v1-my-project-{{ checksum " project.clj"}}

    build-backend:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: 
            - v2-my-project-{{ checksum " project.clj"}}
            - v2-my-project-
        - run:
            name: Back-end build
            command: |
              npm install
              npm run build
              exit 1
        - save_cache:
          paths: 
            - /home/ubuntu/.m2
          key: v2-my-project-{{ checksum " project.clj"}}

workflows : 
  default: 
    jobs:
      - build-frontend
      - build-backend

